server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
    #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StupidTomCat/springcloud-config.git #通过本config-server去用git获取仓库中的yml配置
          #http://localhost:3344/application/test/master或者http://localhost:3344/application-test.yml去访问仓库的yml文件
